# Generated by Django 5.2.7 on 2025-10-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('noun1', models.CharField(max_length=100)),
                ('noun2', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=150)),
                ('verb', models.CharField(max_length=100)),
                ('adjective', models.CharField(max_length=100)),
                ('person', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madlibsStory', models.TextField()),
            ],
        ),
    ]
