# Generated by Django 5.2.7 on 2025-10-09 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MadLibs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='madlibsStory',
            new_name='inputStory',
        ),
    ]
