# Generated by Django 5.2.7 on 2025-10-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MadLibs', '0002_rename_madlibsstory_story_inputstory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='inputStory',
            new_name='tellStory',
        ),
    ]
