# Generated by Django 5.2.7 on 2025-10-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MadLibs', '0003_rename_inputstory_story_tellstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tellStory',
            field=models.CharField(max_length=2000),
        ),
    ]
