# Generated by Django 5.2.7 on 2025-10-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MadLibs', '0006_alter_story_tellstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tellStory',
            field=models.TextField(),
        ),
    ]
